#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import asyncio
import contextlib
import fcntl
import os
import random
import signal
import struct
import sys
import termios

async def _(): f'{await "# Python >= 3.7 is required #"}'

prog = argparse.ArgumentParser().prog

def ushort(s):
    n = int(s)
    try:
        struct.pack('H', n)
    except struct.error:
        raise ValueError
    return n
ushort.__name__ = 'unsigned short int'

if sys.version_info >= (3, 9):
    orig_waitstatus_to_exitcode = os.waitstatus_to_exitcode
    def waitstatus_to_exitcode(status):
        rc = orig_waitstatus_to_exitcode(status)
        if rc < 0:
            rc = signal.Signals(-rc)
            rc.coredump = os.WCOREDUMP(status)
        return rc
    os.waitstatus_to_exitcode = waitstatus_to_exitcode

def main():
    ap = argparse.ArgumentParser()
    ap.color = False
    ap.add_argument('cmd', metavar='COMMAND', nargs='?', help='command to execute')
    ap.add_argument('args', metavar='ARGS', nargs=argparse.REMAINDER, help=argparse.SUPPRESS)
    ap.add_argument('-t', '--tty', help='terminal device to resize (default: stdin)')
    for dim, dimension in dict(wd='width', ht='height').items():
        for lim in ['min', 'max']:
            default = 1 if lim == 'min' else f'original {dimension}'
            ap.add_argument(
                f'--{lim}-{dimension}',
                dest=f'{lim}_{dim}',
                metavar='N', type=ushort,
                help=f'{lim}imum terminal {dimension} (default: {default})'
            )
    ap.add_argument('--interval',
        metavar='N', type=float,
        help='delay between resizes, in seconds (default: no delay)'
    )
    opts = ap.parse_args()
    if opts.tty is None and opts.cmd is None:
        ap.error('-t/--tty or COMMAND is required')
    with contextlib.ExitStack() as ctx:
        if opts.tty:
            fd = os.open(opts.tty, os.O_RDONLY | os.O_NOCTTY)
            ctx.enter_context(os.fdopen(fd, 'rb'))
        else:
            fd = sys.stdin.fileno()
        if not os.isatty(fd):
            print(f'{prog}: {opts.tty or "stdin"} is not a tty')
            sys.exit(-1)
        try:
            opts.sz = sz = os.get_terminal_size(fd)
        except OSError as exc:
            print(f'{prog}: cannot get terminal size: {exc.strerror}', file=sys.stderr)
            sys.exit(-1)
        opts.fd = fd
        min_wd = opts.min_wd = opts.min_wd or 1
        min_ht = opts.min_ht = opts.min_ht or 1
        max_wd = opts.max_wd = opts.max_wd or sz.columns
        max_ht = opts.max_ht = opts.max_ht or sz.lines
        if min_ht > max_ht:
            ap.error(f'min height ({min_ht}) > max height ({max_ht})')
        if min_wd > max_wd:
            ap.error(f'min width ({min_wd}) > max width ({max_wd})')
        asyncio.run(amain(opts))

async def amain(opts):
    opts.queue = asyncio.Queue()
    await asyncio.gather(
        fury(opts),
        run_cmd(opts)
    )

def set_terminal_size(fd, wd, ht):
    winsize = struct.pack('H' * 4, ht, wd, 0, 0)
    fcntl.ioctl(fd, termios.TIOCSWINSZ, winsize)

async def fury(opts):
    fd = opts.fd
    attrs = termios.tcgetattr(fd)
    (orig_wd, orig_ht) = opts.sz
    errmsg = None
    try:
        while True:
            wd = random.randint(opts.min_wd, opts.max_wd)
            ht = random.randint(opts.min_ht, opts.max_ht)
            try:
                set_terminal_size(fd, wd, ht)
            except OSError as exc:
                print(f'{prog}: TIOCSWINSZ with ws_row={ht}, ws_col={wd} failed: {exc.strerror}', file=sys.stderr)
                sys.exit(-1)
            rc = None
            if opts.interval:
                try:
                    rc = await asyncio.wait_for(opts.queue.get(), timeout=opts.interval)
                except asyncio.TimeoutError:
                    pass
            else:
                await asyncio.sleep(0)
            if rc is None and not opts.queue.empty():
                rc = await opts.queue.get()
            if rc is not None:
                if rc < 0:
                    rc = signal.Signals(-rc)
                    rc.coredump = None
                if isinstance(rc, signal.Signals):
                    errmsg = f'{prog}: target program terminated by {rc.name}'
                    if rc.coredump:
                        errmsg += ' (core dumped)'
                    sys.exit(-1)
                elif 0 <= rc <= 0xFF:
                    sys.exit(rc)
                else:
                    raise RuntimeError(f'unexpected return code {rc}')
    finally:
        termios.tcsetattr(fd, termios.TCSAFLUSH, attrs)
        set_terminal_size(fd, orig_wd, orig_ht)
        if errmsg is not None:
            print(errmsg, file=sys.stderr)
            errmsg = None

async def run_cmd(opts):
    if opts.cmd is None:
        return
    proc = await asyncio.create_subprocess_exec(opts.cmd, *opts.args)
    rc = await proc.wait()
    await opts.queue.put(rc)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
